del *.~* /f/q
del *.dcu /f/q
del ..\lib\*.~* /f/q
del ..\lib\*.dcu /f/q
del .\Bot\*.~* /f/q
del .\Bot\*.dcu /f/q
del .\Bot\PokerCombinations\*.~* /f/q
del .\Bot\PokerCombinations\*.dcu /f/q
del .\Common\*.~* /f/q
del .\Common\*.dcu /f/q
del .\DataStore\*.~* /f/q
del .\DataStore\*.dcu /f/q
del .\FileManager\*.~* /f/q
del .\FileManager\*.dcu /f/q
del .\Lobby\*.~* /f/q
del .\Lobby\*.dcu /f/q
del .\Process\*.~* /f/q
del .\Process\*.dcu /f/q
del .\TCPConnection\*.~* /f/q
del .\TCPConnection\*.dcu /f/q
del .\User\*.~* /f/q
del .\User\*.dcu /f/q
del .\Tournament\*.~* /f/q
del .\Tournament\*.dcu /f/q
