del *.~* /f/q
del *.dcu /f/q
del .\Cashier\*.~* /f/q
del .\Cashier\*.dcu /f/q
del .\Common\*.~* /f/q
del .\Common\*.dcu /f/q
del .\DataStore\*.~* /f/q
del .\DataStore\*.dcu /f/q
del .\FileManager\*.~* /f/q
del .\FileManager\*.dcu /f/q
del .\Lobby\*.~* /f/q
del .\Lobby\*.dcu /f/q
del .\Process\*.~* /f/q
del .\Process\*.dcu /f/q
del .\Session\*.~* /f/q
del .\Session\*.dcu /f/q
del .\Server\*.~* /f/q
del .\Server\*.dcu /f/q
del .\User\*.~* /f/q
del .\User\*.dcu /f/q
del .\Tournament\*.~* /f/q
del .\Tournament\*.dcu /f/q
