del *.~*
del *.dcu
del Account\*.~*
del ActionDispatcher\*.~*
del API\*.~*
del Common\*.~*
del Connection\*.~*
del Email\*.~*
del FileManager\*.~*
del SQLAdapter\*.~*
del User\*.~*
del MSMQ\*.~*
del ClientAdapter\*.~*
del GameAdapter\*.~*
del GameConnector\*.~*
del PokerGameEngine\*.~*
del Reminder\*.~*
del Tournament\*.~*
del ..\lib\*.dcu
del ..\lib\*.~*
del ..\ext\*.dcu
del ..\ext\*.~*
